config/routes.rb
Rails.application.routes.draw do
  
  resources :user_stocks, only: [:create, :destroy]
  resources :friendships, only: [:create, :destroy]
  root 'welcome#index'
  devise_for :users
  get 'my_portfolio', to: 'users#my_portfolio'
  get 'my_friends', to: 'users#my_friends'
  get 'search_stock', to: 'stocks#search'
  get 'search_friends', to: 'users#search'
  resources :users, only: [:show]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: "User"
end

app/models/stock.rb
class Stock < ApplicationRecord
  has_many :user_stocks
  has_many :users, through: :user_stocks

  validates :name, :ticker, presence: true
  validates :ticker,
            uniqueness: { case_sensitive: false },
            length: {in: 1..6}

  def self.new_lookup(ticker)
    client = IEX::Api::Client.new(
      publishable_token: Rails.application.credentials.iex_cloud[:sandbox_api_key],
      secret_token: Rails.application.credentials.iex_cloud[:sandbox_secret_api_key],
      endpoint: 'https://sandbox.iexapis.com/v1'
    )
    begin
      new(ticker: ticker.upcase, name: client.company(ticker).company_name, last_price: client.price(ticker))
    rescue => exception
      nil
    end
  end

  def self.get_stock(ticker)
    where(ticker: ticker).first
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_stocks
  has_many :stocks, through: :user_stocks
  has_many :friendships
  has_many :friends, through: :friendships

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def can_track_stock?(ticker)
    under_stock_limit? && !stock_already_tracked?(ticker)
  end

  def under_stock_limit?
    stocks.count < 10
  end

  def stock_already_tracked?(ticker)
    stock = Stock.get_stock(ticker)
    return false unless stock
    stocks.where(id: stock.id).exists?
  end

  def full_name
    return "#{first_name} #{last_name}" if first_name || last_name
    "Anonymous"
  end

  def not_friend_with?(id)
    !self.friends.exists?(id: id)
  end

  def self.search_for_friends(to_search)
    results = search("first_name", to_search) + search("last_name", to_search) + search("email", to_search)
    results.uniq
  end

  private
  def self.search(field, to_search)
    where("#{field} like ?", "%#{to_search}%")
  end

end

app/models/user_stock.rb
class UserStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock

  validates :stock_id, uniqueness: { scope: :user_id,
    message: "This stock is already tracked" }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController

  def create
    new_friend = User.find(params[:friend])
    current_user.friends << new_friend
    flash[:notice] = "You are now following #{new_friend.full_name}."
    redirect_to my_friends_path
  end

  def destroy
    user_to_unfollow = User.find(params[:id])
    friendship = current_user.friendships.where(friend_id: user_to_unfollow).first
    friendship.destroy
    flash[:notice] = "You successfully unfollowed #{user_to_unfollow.full_name}."
    redirect_to my_friends_path
  end

end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  def search
    if (params[:stock]).present?
      @stock = Stock.new_lookup(params[:stock])
      if @stock.nil?
        flash.now[:alert] = "Please enter a valid symbol to search"
      end
    else
      flash.now[:alert] = "Please enter a symbol to search"
    end
    respond_to do |format|
      format.js { render partial: 'users/result' }
    end
  end
end

app/controllers/user_stocks_controller.rb
class UserStocksController < ApplicationController

  def create
    max_stocks = 10
    if current_user.stocks.size >= max_stocks
      raise StandardError.new "You cannot track more than #{max_stocks} stocks"
    end
    stock_to_track = Stock.get_stock(params[:ticker])
    if stock_to_track.nil?
      stock_to_track = Stock.new_lookup(params[:ticker])
      stock_to_track.save
    end
    current_user.stocks << stock_to_track
  rescue ActiveRecord::RecordInvalid => invalid # when a validation does not meet the criterias
    flash[:alert] = invalid.message
  rescue => e
    flash[:alert] = e.message
  else
    flash[:notice] = "You are now tracking the #{stock_to_track.name} stock."
  ensure
    redirect_to my_portfolio_path
  end

  def destroy
    stock = Stock.find(params[:id])
    user_stock = UserStock.where(stock_id: stock.id, user_id: current_user.id).first
    user_stock.destroy
    flash[:notice] = "#{stock.name} was successfully removed from portfolio"
    redirect_to my_portfolio_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def my_portfolio
    @user = current_user
    @stocks = current_user.stocks
  end
  
  def my_friends
    @friends = current_user.friends
  end

  def show
    @user = User.find(params[:id])
    @stocks = @user.stocks
  end
  
  def search
    if (params[:to_search]).present?
      @persons_found = User.search_for_friends(params[:to_search])
      @persons_found.reject! {|user| user == current_user }
      if @persons_found.empty?
        flash.now[:alert] = "Couldn't find users"
      end
    else
      flash.now[:alert] = "Please enter a name or email to search"  
    end
    respond_to do |format|
      format.js { render partial: 'users/result_friends' }
    end
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/user_stocks_helper.rb
module UserStocksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/friends/_list_friends.html.erb
<!-- Friends followed by the user -->
<h3>Friends followed</h3>

<% if !@friends.empty? %>
  <div class="row">
    <div class="col-sm-9">
      <table class="table table-bordered table-hover">
        <thead>
          <tr>
            <th scope="col">Name</th>
            <th scope="col">Email</th>
            <th scope="col">Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @friends.each do |friend| %>
            <tr>
              <td><%= friend.full_name %></td>
              <td><%= friend.email %></td>
              <td>
                <%= link_to "View Profile", user_path(friend), class: "btn btn-sm btn-success" %>
                <%= link_to "Unfollow", friendship_path(friend) , class: "btn btn-sm btn-warning", method: :delete, data: { confirm: "Are you sure you want to unfollow #{friend.full_name} ?" } %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
<% else %>
  <h5>You don't have any friends.</h5>
<% end %>

app/views/layouts/_menu.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Dropdown
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li>
      </ul>
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/_messages.html.erb
<% if notice %>
  <div class="alert alert-success">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <%= notice %>
  </div> 
<% end %>

<% if alert %>
  <div class="alert alert-danger">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <%= alert %>
  </div> 
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <%= link_to "FinanceTracker", root_path, class: "navbar-brand" %> 
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <% if user_signed_in? %>
        <ul class="navbar-nav mr-auto">
          <li class="nav-item <%= 'active' if request.path == my_portfolio_path %> ">
            <%= link_to "My portfolio", my_portfolio_path, class: "nav-link" %>
          </li>
          <li class="nav-item <%= 'active' if request.path == my_friends_path %> ">
            <%= link_to "My friends", my_friends_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= form_with url: search_stock_path, class: "form-inline my-2 my-lg-0", local: false, method: :get do |form| %>
              <%= form.text_field :stock, placeholder: "Stock ticker symbol", class: "form-control", autocomplete: "off" %> 
              <%= form.submit "Search", class: "btn btn-outline-success" %>
            <% end %>
          </li>
        </ul>

        <ul class="navbar-nav ml-auto">
          <li class="nav-item dropdown active">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= fa_icon "user" %> <%= current_user.full_name %>
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to edit_user_registration_path, class: "dropdown-item" do %>
                <%= fa_icon "edit" %> Edit my profile
              <% end %>
              <div class="dropdown-divider"></div>
              <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        </ul>
      <% end %>
      
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinanceTracker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <div class="container"> 
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/stocks/_list.html.erb
<!-- Stocks tracked by the user -->
<h3>Stocks tracked</h3>

<% if !@stocks.empty? %>
  <div class="row">
    <div class="col-sm-9">
      <table class="table table-bordered table-hover">
        <thead>
          <tr>
            <th scope="col">Ticker Symbol</th>
            <th scope="col">Company Name</th>
            <th scope="col">Last Price</th>
            <th scope="col">Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @stocks.each do |stock| %>
            <tr>
              <td><%= stock.ticker %></td>
              <td><%= stock.name %></td>
              <td><%= stock.last_price %></td>
              <% if @user == current_user %>
                <td>
                  <%= link_to "Untrack", user_stock_path(stock) , class: "btn btn-sm btn-warning", method: :delete, data: { confirm: "Are you sure you want to untrack #{stock.name} ?" } %>
                </td>
              <% else %>
                <td>
                  <%= render 'stocks/track_stock', stock: stock %>
                </td> 
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
<% else %>
  <h5>No stocks are currently tracked</h5>
<% end %>

app/views/stocks/_track_stock.html.erb
<% if current_user.can_track_stock?(stock.ticker) %>
  <%= link_to "Track this stock", user_stocks_path(user: current_user, ticker: stock.ticker), class: "btn btn-sm btn-success", method: :post %>
<% else %>
  <span class="badge badge-secondary">
    <% if current_user.stock_already_tracked?(stock.ticker) %>
      You are already tracking this stock
    <% else %>
      You cannot track more than 10 stocks
    <% end %>
  </span>
<% end %>  

app/views/users/_result.html.erb
<div class="results-block">
  <%= render 'layouts/messages' %>
</div>

<% if @stock %>
  <div class="card card-header results-block">
    <strong>Symbol: </strong> <%= @stock.ticker %>
    <strong>Company name: </strong> <%= @stock.name %>
    <strong>Last price: </strong> <%= @stock.last_price %> 
    <%= render 'track_stock', stock: @stock %>  
  </div>
<% end %>

app/views/users/_result.js.erb
document.querySelector('#results').innerHTML = "<%= j render 'users/result.html' %>"  
/* j (which is an alias for the escape_javascript method) is used to escape whatever will be returned by the ruby code 
   to make sure that everything between the quotes will be valid and that the string will not be broken. Example:
   document.querySelector("#reviews").innerHTML = "<a href="/mycontroller/myaction">Action!</a>" */

app/views/users/_result_friends.html.erb
<div class="results-block">
  <%= render 'layouts/messages' %>
</div>


<% if @persons_found && !@persons_found.empty? %>
  <div class="card card-header results-block">
    <table class="col-md-12">
      <tbody>
        <% @persons_found.each do |person| %>
          <tr>
            <td><strong>Name: </strong><%= person.full_name %></td>
            <td><strong>Email: </strong><%= person.email %></td>
            <td><strong>Actions: </strong>
              <%= link_to "View Profile", user_path(person), class: "btn btn-sm btn-success" %>
              <% if current_user.not_friend_with?(person.id) %>
                <%= link_to "Follow this friend", friendships_path(friend: person), class: "btn btn-sm btn-success", method: :post %>
              <% else %>
                Already friends
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% end %>

app/views/users/_result_friends.js.erb
document.querySelector('#results-friends').innerHTML = "<%= j render 'users/result_friends.html' %>"  
/* j (which is an alias for the escape_javascript method) is used to escape whatever will be returned by the ruby code 
   to make sure that everything between the quotes will be valid and that the string will not be broken. Example:
   document.querySelector("#reviews").innerHTML = "<a href="/mycontroller/myaction">Action!</a>" */

app/views/users/my_friends.html.erb
<h1>My friends</h1>

<div class="search-area">
  <h3>Search friends</h3>
  <%= form_with url: search_friends_path, local: false, method: :get do |form| %>
    <div class="form-group row">
      <div class="col-sm-9 no-right-padding">
        <%= form.text_field :to_search, placeholder: "Name or Email", autofocus: true, class: "form-control form-control-lg", autocomplete: "off" %>        
      </div>
      <div class="col-sm-3 no-left-padding">
        <%= button_tag class: "btn btn-success" do %>
          <%= fa_icon "search 2x" %>
        <% end %> 
      </div>
    </div>
  <% end %>
</div>

<!-- For JS results -->
<div id="results-friends">
</div>

<%= render 'friends/list_friends' %>

app/views/users/my_portfolio.html.erb
<h1>My portfolio</h1>

<div class="search-area">
  <h3>Search stocks</h3>
  <%= form_with url: search_stock_path, local: false, method: :get do |form| %>
    <div class="form-group row">
      <div class="col-sm-9 no-right-padding">
        <%= form.text_field :stock, placeholder: "Stock ticker symbol", autofocus: true, class: "form-control form-control-lg", autocomplete: "off" %>        
      </div>
      <div class="col-sm-3 no-left-padding">
        <%= button_tag class: "btn btn-success", data: { disable_with: "<i class='fa fa-circle-o-notch fa-spin fa-2x'></i>".html_safe } do %>
          <%= fa_icon "search 2x" %>
        <% end %> 
      </div>
    </div>
  <% end %>
</div>

<!-- For JS results -->
<div id="results">
</div>

<%= render 'stocks/list' %>

app/views/users/show.html.erb
<div class="row">
  <div class="col-sm-6">
    <div class="jumbotron">
      <h1 class="display-4"><%= @user.full_name %></h1>
      <p class="lead">Email: <%= @user.email %></p>
    </div>
  </div>
</div>


<%= render 'stocks/list' %>

app/views/welcome/index.html.erb
<h1>Welcome to finance tracker app</h1>
<p>Find me in app/views/welcome/index.html.erb</p>

<%= link_to "Sign out", destroy_user_session_path, method: :delete %>